import Vue from 'vue'
import {
    Button,
    Badge,
    Cascader,
    Checkbox,
    CheckboxGroup,
    Dialog,
    DatePicker,
    Dropdown,
    DropdownMenu,
    DropdownItem,
    Form,
    FormItem,
    Input,
    Icon,
    Option,
    Popover,
    Pagination,
    Select,
    Table,
    Tag,
    TableColumn,
} from 'element-ui'
import '../scss/element-variables.scss'
Vue.use(Button),
    Vue.use(Badge),
    Vue.use(Cascader),
    Vue.use(Checkbox),
    Vue.use(CheckboxGroup),
    Vue.use(Dialog),
    Vue.use(Dropdown),
    Vue.use(DropdownMenu),
    Vue.use(DropdownItem),
    Vue.use(DatePicker),
    Vue.use(Form),
    Vue.use(FormItem),
    Vue.use(Input),
    Vue.use(Icon),
    Vue.use(Option),
    Vue.use(Popover),
    Vue.use(Pagination),
    Vue.use(Select),
    Vue.use(Table),
    Vue.use(Tag),
    Vue.use(TableColumn)
